# Site settings
title: kalkin7
email: kalkin7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kalkin7's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blogtest04.kalkinblog.tk" # the base hostname & protocol for your site
twitter_username: kalkin_7
github_username:  kalkin7

# Build settings
markdown: kramdown

permalink: /post/:title

sass:
  sass_dir: _sass
  style: :compressed
